name: house_number_proj
channels:
  - pytorch
  - defaults
dependencies:
  - h5py=3.5.0
  - numpy=1.21.2
  - python=3.8.8
  - scipy=1.7.1
  - pytorch=1.10
  - torchvision=0.11.1
  - pip:
    - scikit-learn==1.0.1
    - opencv-python==4.5.4.58    